export const updateTimelineItemActivitySecondsKey = Symbol()
export const setActivitySecondToCompleteKey = Symbol()
export const setTimelineItemActivityKey = Symbol()
export const createActivityKey = Symbol()
export const deleteActivityKey = Symbol()
export const activitySelectOptionsKey = Symbol()
export const periodSelectOptionsKey = Symbol()
export const timelineItemsKey = Symbol()